### ISSUE TITLE
Last couple of commits are only compatible with Roasbeef fork? 

### ISSUE THREAD

**Issue by grisha** [btcsuite/btcutil#103]
```
# github.com/btcsuite/btcutil
./block.go:82: b.msgBlock.SerializeNoWitness undefined (type *wire.MsgBlock has no field or method SerializeNoWitness)
./tx.go:63: t.msgTx.WitnessHash undefined (type *wire.MsgTx has no field or method WitnessHash)
./tx.go:77: t.msgTx.HasWitness undefined (type *wire.MsgTx has no field or method HasWitness)
```

**Comment by davecgh** [comment]
The commits in btcd that the latest commits rely on have not been merged to btcd yet.  They will be soon.  In the mean time, your build environment should be used the locked dependency versions specified in the btcd `glide.lock` file (aka before these latest commits).

**Comment by romanornr** [comment]
hi btcrpcclient depends on it.

Maybe it's an idea to create another branch for untested code or code that doesn't pass Travis.

**Comment by romanornr** [comment]
````
hash: 9e111ebb6989c8b23db0ef5c0523e8dde1ccaa964fa7a42faccbb7a6a60b2860
updated: 2017-06-19T16:45:22.5258215-04:00
imports:
- name: github.com/btcsuite/btcrpcclient
  version: 45b9cb481d2aead4e80aab32d7aa86db386430ab
- name: github.com/btcsuite/btcutil
  version: dcd4997b0664bcfd6ef48e4ae9da8396e08b1cd9
````
After running ````glide install````
I still got the same erros. Not sure if I do anything wrong.

Lock files looks like this

````
hash: bdf5c0b43903ad8f1246f2cdfe547d87d5dcc3a4055c326109e5a2a40514e3e3
updated: 2017-07-28T18:29:38.544078261+02:00
imports:
- name: github.com/btcsuite/btcd
  version: 47885ab8702485be6b6f87a03d4f3be0bc5c982c
  subpackages:
  - btcec
  - btcjson
  - chaincfg
  - chaincfg/chainhash
  - wire
- name: github.com/btcsuite/btclog
  version: 84c8d2346e9fc8c7b947e243b9c24e6df9fd206a
- name: github.com/btcsuite/btcrpcclient
  version: 0d9ec835baeb9a8ce7fbe3eb7d7783284a089ced
- name: github.com/btcsuite/btcutil
  version: dcd4997b0664bcfd6ef48e4ae9da8396e08b1cd9
  subpackages:
  - base58
- name: github.com/btcsuite/go-socks
  version: 4720035b7bfd2a9bb130b1c184f8bbe41b6f0d0f
  subpackages:
  - socks
- name: github.com/btcsuite/websocket
  version: 31079b6807923eb23992c421b114992b95131b55
- name: golang.org/x/crypto
  version: 27b9897dfcda296fc086003b6e46fca80a29512d
  subpackages:
  - ripemd160
testImports: []
````
